### ISSUE TITLE
Syntax for Strings

### ISSUE THREAD

**Issue by juanibiapina** [race-lang/race#16]
Basic stuff to get strings rolling:

### Syntax:

- Always use double quotes
- Single line only (at least for now)

### Example:

```
"Well, hello mr fancy pants!"
```

Thoughts?

**Comment by hmleal** [comment]
:+1:

**Comment by jonathansp** [comment]
We should start thinking about chars, not strings.

**Comment by juanibiapina** [comment]
@jonathansp I like it.

**Comment by juanibiapina** [comment]
Regardless of how we implement them (strings could be native or a list of chars), this step is only about the syntact structure, so I can write the parser.
